🐛 :fix Fixing CI-CD

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -9,37 +9,27 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      # Upgrade checkout action
-      - name: Checkout
+      - name: Checkout Code
         uses: actions/checkout@v2
         with:
           ref: main
 
-      # Install OpenVPN
-      - name: Install OpenVPN
+      - name: Install OpenVPN and Check VPN
         run: |
           sudo apt update
           sudo apt install -y openvpn openvpn-systemd-resolved
+          echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn
+          openvpn --config vpn_config.ovpn --daemon
+          sleep 10
+          ifconfig | grep tun0 || { echo "VPN connection failed"; exit 1; }
 
-      # Create VPN Config File
-      - name: Create VPN Config File
-        run: echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn
-
-      # Connect to VPN
-      - name: Connect to VPN
-        uses: "kota65535/github-openvpn-connect-action@v2"
-        with:
-          config_file: vpn_config.ovpn
-
-      # Test SSH Connection
       - name: Test SSH Connection
         run: |
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key
           chmod 600 /tmp/private_key
           ssh -vvv -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} whoami
 
-      # Build & Deploy
-      - name: Deploy to remote server
+      - name: Deploy to Server
         uses: easingthemes/ssh-deploy@main
         with:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
@@ -49,12 +39,12 @@ jobs:
           TARGET: "/home/debian/Documents/jouskaio.me/WEB-Jouskaio.me"
           EXCLUDE: "/dist/, /node_modules/"
           SCRIPT_AFTER: |
-            echo "Starting SCRIPT_AFTER"
+            set -e
             export NVM_DIR="$HOME/.nvm"
             [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
             cd /home/debian/Documents/jouskaio.me/WEB-Jouskaio.me
-            git pull
-            yarn install
+            git fetch --all
+            git reset --hard origin/main
+            if [ ! -d "node_modules" ]; then yarn install; fi
             yarn build
-            pm2 restart WEB-Jouskaio.me
-            
+            pm2 reload ecosystem.config.js --env production
